version: "2.1"

services:
  db-node-1:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: db-node-1
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: '1'
      MARIADB_DATABASE: archdb
      MARIADB_USER: stud
      MARIADB_PASSWORD: stud
    networks:
      - arch-network
    ports:
      - 3360:3306
    volumes:
      - db-node-1-data:/var/lib/mysql
  
  db-node-2:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: db-node-2
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: '1'
      MARIADB_DATABASE: archdb
      MARIADB_USER: stud
      MARIADB_PASSWORD: stud
    networks:
      - arch-network
    ports:
      - 3361:3306
    volumes:
      - db-node-2-data:/var/lib/mysql

  proxysql:
    build:
      context: proxysql
      dockerfile: Dockerfile
    container_name: proxysql
    command: >
      --initial
    volumes:
      - proxysql-data:/var/lib/proxysql
    healthcheck:
      test: "/usr/bin/mysql --user=stud --password=stud --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 5
    depends_on:
      - db-node-1
      - db-node-2

    networks:
      - arch-network
    ports:
      # Mysql Client Port
      - "6033:6033"
      # Mysql Admin Port
      - "6032:6032"
  authorization_service:
    build:
      context: authorization_service
      dockerfile: Dockerfile
    container_name: authorization_service
    environment:
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=archdb
      - SERVICE_PORT=8080
      - LD_LIBRARY_PATH=/usr/local/lib
    ports:
      - 8080:8080
    networks:
      - arch-network
    depends_on:
      - proxysql
      
volumes:
  db-node-1-data:
  db-node-2-data:
  proxysql-data:

networks:
  arch-network:
    driver: "bridge"
    external: false
