version: "3.3"

services:
  mariadb-1:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: messenger
      MARIADB_USER: test_admin
      MARIADB_PASSWORD: password
    networks:
      - arch-network
    ports:
      - 3360:3306
    healthcheck:
      test: [
        "CMD",
        "mariadb",
        "--user=test_admin",
        "--password=password",
        "--execute=SELECT * FROM users",
        "--host=127.0.0.1",
        "--port=3306",
        "messenger"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mariadb-1-data:/var/lib/mysql
      # bind-mount any sql files that should be run while initializing
      - ./scripts/creation.sql:/docker-entrypoint-initdb.d/creation.sql
      - ./scripts/insertion.sql:/docker-entrypoint-initdb.d/insertion.sql
  mariadb-2:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: messenger
      MARIADB_USER: test_admin
      MARIADB_PASSWORD: password
    networks:
      - arch-network
    ports:
      - 3361:3306
    healthcheck:
      test: [
        "CMD",
        "mariadb",
        "--user=test_admin",
        "--password=password",
        "--execute=SELECT * FROM users",
        "--host=127.0.0.1",
        "--port=3306",
        "messenger"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mariadb-2-data:/var/lib/mysql
      # bind-mount any sql files that should be run while initializing
      - ./scripts/creation.sql:/docker-entrypoint-initdb.d/creation.sql
      - ./scripts/insertion.sql:/docker-entrypoint-initdb.d/insertion.sql
  proxysql:
    build:
      context: proxysql
      dockerfile: Dockerfile
    container_name: proxysql
    command: >
      --initial
    volumes:
      - proxysql-data:/var/lib/proxysql
    healthcheck:
      test: "/usr/bin/mysql --user=stud --password=stud --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 5
    depends_on:
      - mariadb-1
      - mariadb-2

    networks:
      - arch-network
    ports:
      # Mysql Client Port
      - "6033:6033"
      # Mysql Admin Port
      - "6032:6032"

volumes:
  mariadb-1-data:
  mariadb-2-data:
  proxysql-data:

networks:
  arch-network:
    driver: "bridge"
    external: false
