openapi: '3.0.0'

info:
  title: "P2p Chat Service API"
  description: "API для задания по курсу Архитектура программных систем"
  version: "1.0"

servers:
- url: "http://localhost:8082"
  description: "P2p Chat Server"

paths:
  /add/message:
    post:
      summary: "Добавление сообщения в P2P чат"
      parameters:
        - $ref: '#/components/parameters/sender_id'
        - $ref: '#/components/parameters/receiver_id'
        - $ref: '#/components/parameters/text'
      responses:
        200:
          description: "Идентификатор добавленного сообщения"
          content:
            application/json:
              schema:
                type: integer
        400:
          description: "Ошибка в параметрах запроса"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: "Сообщение не добавлено"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: "Неожиданная ошибка"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'    
  /create:
    post:
      summary: "Создание P2P чата"
      parameters:
        - $ref: '#/components/parameters/user_id1'
        - $ref: '#/components/parameters/user_id2'
      responses:
        200:
          description: "Идентификатор созданного P2P чата"
          content:
            application/json:
              schema:
                type: integer
        400:
          description: "Ошибка в параметрах запроса"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: "Неожиданная ошибка"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /load:
    get:
      summary: "Загрузка сообщений P2P чата"
      parameters:
        - $ref: '#/components/parameters/user_id1'
        - $ref: '#/components/parameters/user_id2'
      responses:
        200:
          description: "Загруженные сообщения P2P чата"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messages'
        400:
          description: "Ошибка в параметрах запроса"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: "Сообщения не найдены"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: "Неожиданная ошибка"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  
  parameters:
    user_id1:
      name: user_id1
      description: "Уникальный идентификатор первого пользователя"
      in: query
      required: true
      schema:
        type: integer
    user_id2:
      name: user_id2
      description: "Уникальный идентификатор второго пользователя"
      in: query
      required: true
      schema:
        type: integer
    sender_id:
      name: sender_id
      description: "Уникальный идентификатор отправителя сообщения"
      in: query
      required: true
      schema:
        type: integer
    receiver_id:
      name: receiver_id
      description: "Уникальный идентификатор получателя сообщения"
      in: query
      required: true
      schema:
        type: integer
    text: 
      name: text
      description: "Текст сообщения"
      in: query
      required: true
      schema:
        type: string
  
  schemas:
    message:
      type: object
      required:
        - message_id
        - chat_id
        - user_id
      properties:
        message_id:
          type: integer
        chat_id:
          type: integer
        user_id:
          type: integer
        text:
          type: string
        date_time:
          type: string
    messages:
      type: array
      items:
        $ref: '#/components/schemas/message'
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: "Сообщение о ошибке"
          type: string
