openapi: '3.0.0'

info:
  title: "Group Chat Service API"
  description: "API для задания по курсу Архитектура программных систем"
  version: "1.0"

servers:
- url: "http://localhost:8081"
  description: "Group Chat Server"

paths:
  /add/message:
    post:
      summary: "Добавление сообщения в групповой чат"
      parameters:
        - $ref: '#/components/parameters/chat_id'
        - $ref: '#/components/parameters/login'
        - $ref: '#/components/parameters/text'
      responses:
        200:
          description: "Идентификатор добавленного сообщения"
          content:
            application/json:
              schema:
                type: integer
        400:
          description: "Ошибка в параметрах запроса"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: "Сообщение не добавлено"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: "Неожиданная ошибка"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /add/user:
    post:
      summary: "Добавление пользователя в групповой чат"
      parameters:
        - $ref: '#/components/parameters/login'
        - $ref: '#/components/parameters/chat_id'
      responses:
        200:
          description: "Пользователь добавлен"
        400:
          description: "Ошибка в параметрах запроса"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: "Неожиданная ошибка"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /create:
    post:
      summary: "Создание группового чата"
      parameters:
        - $ref: '#/components/parameters/title'
      responses:
        200:
          description: "Идентификатор созданного группового чата"
          content:
            application/json:
              schema:
                type: integer
        400:
          description: "Ошибка в параметрах запроса"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: "Неожиданная ошибка"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /load:
    get:
      summary: "Загрузка сообщений группового чата"
      parameters:
        - $ref: '#/components/parameters/chat_id'
      responses:
        200:
          description: "Загруженные сообщения группового чата"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messages'
        400:
          description: "Ошибка в параметрах запроса"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: "Сообщения не найдены"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: "Неожиданная ошибка"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:

  parameters:
    login:
      name: login
      description: "Логин пользователя"
      in: query
      required: true
      schema:
        type: string
    chat_id:
      name: chat_id
      description: "Уникальный идентификатор группового чата"
      in: query
      required: true
      schema:
        type: integer
    text:
      name: text
      description: "Текст сообщения"
      in: query
      required: true
      schema:
        type: string
    title:
      name: title
      description: "Название группового чата"
      in: query
      required: true
      schema:
        type: string

  schemas:
    message:
      type: object
      required:
        - message_id
        - chat_id
        - user_id
      properties:
        message_id:
          type: integer
        chat_id:
          type: integer
        user_id:
          type: integer
        text:
          type: string
        date_time:
          type: string
    messages:
      type: array
      items:
        $ref: '#/components/schemas/message'
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: "Сообщение о ошибке"
          type: string
  