version: "2.1"

services:
  mariadb:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: messenger
      MARIADB_USER: test_admin
      MARIADB_PASSWORD: password
    networks:
      - arch-network
    ports:
      - 3306:3306
    healthcheck:
      test: [
        "CMD",
        "mariadb",
        "--user=test_admin",
        "--password=password",
#        "--execute=SELECT * FROM users",
        "--host=127.0.0.1",
        "--port=3306",
        "messenger"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      # persist data files into `datadir` volume managed by docker
      - datadir:/var/lib/mysql
      # bind-mount any sql files that should be run while initializing
      - ./scripts/creation.sql:/docker-entrypoint-initdb.d/creation.sql
      - ./scripts/insertion.sql:/docker-entrypoint-initdb.d/insertion.sql
  web_server:
    build:
      context: web_server
      dockerfile: Dockerfile
    container_name: web_server
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_LOGIN=test_admin
      - DB_PASSWORD=password
      - DB_DATABASE=messenger
      - LD_LIBRARY_PATH=/usr/local/lib
    ports:
      - 8080:8080
    networks:
      - arch-network
    depends_on:
      mariadb:
        condition: service_healthy
  other_server:
    build:
      context: other_server
      dockerfile: Dockerfile
    container_name: other_server
    environment:
      - SERVICE_HOST=web_server
      - LD_LIBRARY_PATH=/usr/local/lib
    ports:
      - 8081:8081
    networks:
      - arch-network

volumes:
  datadir:

networks:
  arch-network:
    driver: "bridge"
    external: false
